bus:
  market_data_capacity : 1024
  signal_capacity : 256
  approved_capacity : 256

source:

  type: "yahoo"
  
  params:
    symbols : ["GOOG"]
    start : "2021-01-01"
    end : "2022-01-01"
    interval: "1d"


strategy:

  type: "random_pt"

  params:
    listener_id : "random"
    symbols : ["GOOG"]

risk:

  type: "passthrough"

  params:
    listener_id: "passthrough_risk"

execution:

  type: "simulation"

  params:
    listener_id : "sim_exec"
    
