bus:
  market_data_capacity: 1024
  signal_capacity: 256
  approved_capacity: 256

source:
  type: "file_replay"
  params:
    filepath: "data/raw/btcusdt_20250316.jsonl"
    data_cls: "OrderBookEntry"

strategy:
  type: "rsi"
  params:
    listener_id: "rsi_strategy"
    symbols: ["btcusdt"]
    rsi_period: 14
    overbought: 90.0
    oversold: 10.0
    vwmp: true

risk:
  type: "passthrough"
  params:
    listener_id: "passthrough_risk"

execution:
  type: "simulation"
  params:
    listener_id: "sim_exec"
